i18n/i18n_module_fr.properties
Merge translations from translation server.
=> Translations.

index.html, package.json, src/apps-app.js, webpack-base-config.js
Upgraded from Babel 5.x to Babel 6.x
=> Upgraded from Babel 5.x to Babel 6.x

i18n/i18n_module_es.properties
Thanks to ccaceres  for these.
=> Syncing Spanish translations.

README.md, src/components/AppList.component.js
* Caused by using onTouchTap which is deprecated in MUI 0.19.2
=> Fix app opening when attempting to uninstall

package.json, yarn.lock
This fixes a build issue.
Build is now succeeding https://travis-ci.com/dhis2/app-management-app/builds/122955011
And was failing before https://travis-ci.com/dhis2/app-management-app/builds/122943968
=> chore(dependencies): upgraded i18n packages

i18n/vi.po
=> chore(translations): sync Vietnamese translations from transifex (master)

i18n/sv.po
=> chore(translations): sync Swedish translations from transifex (master)

i18n/ru.po
=> chore(translations): sync Russian translations from transifex (master)

i18n/fr.po
=> chore(translations): sync French translations from transifex (master)

i18n/vi.po
=> chore(translations): sync Vietnamese translations from transifex (v32)

i18n/sv.po
=> chore(translations): sync Swedish translations from transifex (v32)

i18n/ru.po
=> chore(translations): sync Russian translations from transifex (v32)

i18n/fr.po
=> chore(translations): sync French translations from transifex (v32)

i18n/vi.po
=> chore(translations): sync Vietnamese translations from transifex (v33)

i18n/ru.po
=> chore(translations): sync Russian translations from transifex (v33)

i18n/fr.po
=> chore(translations): sync French translations from transifex (v33)

src/actions.js
(cherry picked from commit 5e35a099d90eb03a596befb35b494dfa680419c4)
=> fix: [36] use core AppHub proxy instead of apps.dhis2.org

src/components/AppList.component.js
Java serialization is changing in dhis2/dhis2-core#6111
=> fix: use `bundled` instead of `isBundledApp`

.tx/config, i18n/en.pot, public/i18n_legacy/i18n_module_en.properties, src/AppWrapper.js, src/actions.js, src/components/AppList.component.js
Backport of https://github.com/dhis2/app-management-app/pull/199
https://jira.dhis2.org/browse/DHIS2-10630
=> fix: translate headers, menu actions, searchbar, and 'missing' messages (v36)

.tx/config, i18n/en.pot, public/i18n_legacy/i18n_module_en.properties, src/AppWrapper.js, src/actions.js, src/components/AppList.component.js
Backport of https://github.com/dhis2/app-management-app/pull/199
https://jira.dhis2.org/browse/DHIS2-10630
=> fix: translate headers, menu actions, searchbar, and 'missing' messages (v35)

d2.config.js, package.json, src/.babelrc.js, src/components/SelfUpdateNoticeBox.component.js, src/utils/versions.js, src/utils/versions.test.js
Backport to 2.35 of #127 (actually #215)
=> fix: (2.35) correctly compare versions to find the latest version on app hub [DHIS2-10859]
